services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=root:root@tcp(db:3306)/project?charset=utf8mb4&parseTime=True&loc=Local
      - APP_ENV=prod
    depends_on:
      db: 
        condition: service_healthy
    restart: on-failure
    
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    
