services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=root:dbpassword@tcp(db:3306)/go-project?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - db
    
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
    
